### ISSUE TITLE
Error when running `yarn start`

### ISSUE THREAD

**Issue by okeefm** [synthetichealth/caremaps-react#20]
When I run `yarn start` in `master`, I get the following error:

    Error: Could not find or load main class start
    Caused by: java.lang.ClassNotFoundException: start

**Comment by arscan** [comment]
Sounds like you aren't running `yarn` the javascript package manager.  Perhaps you are running `yarn` from hadoop-yarn?  You could either install [yarn](https://yarnpkg.com) or just use npm instead... `npm install && npm start`.

I wonder if the community has moved past yarn, now that npm has incorporated many of its features.  A quick survey of todays trending GitHub javascript repos seems to indicate npm is much more popular these days.

**Comment by schreiaj** [comment]
Closing as resolved
