### ISSUE TITLE
Fix error with JSON upload

### ISSUE THREAD

**Issue by kjmahalingam** [synthetichealth/caremaps-react#76]
A bug exists where the JSON upload of a module sometimes causes the module builder to crash. This should be fixed.

**Comment by arscan** [comment]
I cannot recreate this issue.  I reviewed the code and made a bunch of improvements (see the PR referenced above) but I'm unsure if it fixed the underlying problem.  I saw this come up in the demo, so I know it happens somehow, but for whatever reason the way I use the interface cannot trigger the problem.  Any suggestions?

**Comment by arscan** [comment]
I'm going to close this issue for now because we can't recreate it and I added code to make this more robust in #87.  We will keep an eye out for this problem and open a new issue if necessary.
